name: Deploy to Railway

on:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Railway CLI
        run: npm install -g @railway/cli
      - name: Deploy
        run: |
          railway up --project 9eabd329-9209-46d9-94bf-fad266664d00 --environment 8df6f2af-fed6-49d0-8b76-be21f958b42b --service=la-mystique-divine --detach
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
